(() => {
  'use strict';

  const C = { bg:'#071018', panel:'#101f2c', text:'#eaf2f7', muted:'#9cb0bd', accent:'#53d3a7', blue:'#6ca8ff', amber:'#e9b75b', violet:'#b293ff', danger:'#f27f7f' };

  const BLOCKS = [
    { id:'identity', title:'Identity & typing', group:'identity', summary:'Stable id, ORBIT and schema versions, contract status, node type, orientation level and title.', fields:['id','orbit_version','schema_version','contract_status','node_type','orbit_level','title'], invariant:'Unknown undeclared core fields fail. L0 is source material and is not a valid orientation-node level.' },
    { id:'scope', title:'Scope contract', group:'identity', summary:'Declares the domain, what the node covers and what it explicitly excludes.', fields:['scope.domain','scope.covers[]','scope.excludes[]'], invariant:'Exclusion is a contract, not an inference.' },
    { id:'payload', title:'Orientation payload', group:'identity', summary:'A bounded summary and why the node matters to a consumer.', fields:['payload.summary','payload.why_it_matters'], invariant:'The payload orients. It does not replace source evidence.' },
    { id:'links', title:'Three edge planes', group:'graph', summary:'Structural containment, query-intent routing and lateral semantic association remain separate.', fields:['links.structural','links.routing','links.semantic'], invariant:'Structural edges must remain acyclic. Semantic and routing cycles may exist under bounded traversal rules.' },
    { id:'horizon', title:'Horizon', group:'graph', summary:'Locates the node against a root index, nearest orientation map, global position and root paths.', fields:['horizon.root_index','nearest_orientation_map','global_position','root_paths[]'], invariant:'A node must remain globally orientable, not just locally descriptive.' },
    { id:'provenance', title:'Provenance barrier', group:'authority', summary:'Distinguishes source truth from derived orientation and names the evidence behind derived nodes.', fields:['provenance.source_truth','derived_from[]','derivation_method'], invariant:'A derived node may orient and navigate, but may not be cited as source truth.' },
    { id:'epistemic', title:'Epistemic state', group:'authority', summary:'Freshness, confidence, coverage and claim authority describe content quality.', fields:['epistemic.freshness','confidence','coverage','claim_authority'], invariant:'Confidence cannot override provenance or structural drift.' },
    { id:'sync', title:'Sync state', group:'authority', summary:'Records structural or source drift separately from content freshness.', fields:['sync.state','sync.reason','sync.last_checked'], invariant:'A node may be epistemically strong and structurally dirty at the same time.' },
    { id:'invalidation', title:'Invalidation policy', group:'authority', summary:'Pairs low, medium, high or critical severity with safe-use and regeneration policy.', fields:['severity','safe_to_use_as','regeneration_policy','affected_sources[]'], invariant:'Critical invalidation is not_safe and requires immediate regeneration.' },
    { id:'anchors', title:'Anchor invariant', group:'projection', summary:'Protects required domain terms or approved aliases against compression washout.', fields:['required terms','aliases','entities','forbidden generalizations','anchor policy'], invariant:'Strict-literal survival is required. A range such as T1 to T7 does not preserve T6 unless T6 is named.' },
    { id:'briefs', title:'Consumer briefs', group:'projection', summary:'Authored brief surfaces for small LLM, agent and human consumers.', fields:['consumer_briefs.small_llm','consumer_briefs.agent','consumer_briefs.human'], invariant:'Each target has its own bounded orientation surface.' },
    { id:'budget', title:'Budget contract', group:'projection', summary:'Separates the backend authoring target and maximum from hard per-target projection gates.', fields:['tokenizer_profile','target_tokens','max_tokens','projection_gate_tokens'], invariant:'A missing target gate fails loud. There is no fallback to max_tokens.' }
  ];

  function color(group) { return group === 'identity' ? C.blue : group === 'graph' ? C.violet : group === 'authority' ? C.amber : C.accent; }
  function roundedRect(ctx,x,y,w,h,r){const q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath();}
  function wrapText(ctx,text,maxWidth){const words=text.split(/\s+/),lines=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(line&&ctx.measureText(test).width>maxWidth){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines;}
  function point(canvas,event){const rect=canvas.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top};}
  function hiDpi(canvas,draw){const resize=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);draw(ctx,rect.width,rect.height)};new ResizeObserver(resize).observe(canvas);resize();return resize;}
  function arrow(ctx,a,b,col='rgba(156,176,189,.46)',dashed=false,label=''){const angle=Math.atan2(b.y-a.y,b.x-a.x),ar=a.r||Math.max(a.w||50,a.h||50)/2,br=b.r||Math.max(b.w||50,b.h||50)/2,sx=a.x+Math.cos(angle)*ar*.82,sy=a.y+Math.sin(angle)*ar*.82,ex=b.x-Math.cos(angle)*br*.82,ey=b.y-Math.sin(angle)*br*.82;ctx.save();ctx.strokeStyle=col;ctx.lineWidth=1.8;if(dashed)ctx.setLineDash([7,6]);ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(ex,ey);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(ex,ey);ctx.lineTo(ex-Math.cos(angle-Math.PI/6)*9,ey-Math.sin(angle-Math.PI/6)*9);ctx.lineTo(ex-Math.cos(angle+Math.PI/6)*9,ey-Math.sin(angle+Math.PI/6)*9);ctx.closePath();ctx.fill();if(label){ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillStyle=C.muted;ctx.fillText(label,(sx+ex)/2,(sy+ey)/2-6)}ctx.restore();}
  function setupScroll(){document.querySelectorAll('[data-scroll-target]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.scrollTarget)?.scrollIntoView({behavior:'smooth',block:'start'})));}

  function initNodeCanvas(){
    const canvas=document.getElementById('nodeCanvas'),detail=document.getElementById('nodeDetail');if(!canvas||!detail)return;
    let nodes=[],bounds={width:0,height:0},selected='identity',dragging=null,offset={x:0,y:0};
    function reset(){const mobile=bounds.width<700;nodes=BLOCKS.map((b,i)=>{const col=i%3,row=Math.floor(i/3);return{...b,w:154,h:72,x:mobile?bounds.width/2:92+col*(bounds.width-184)/2,y:mobile?60+i*79:62+row*(bounds.height-124)/3}});draw();}
    function update(){const b=BLOCKS.find(x=>x.id===selected)||BLOCKS[0];detail.querySelector('h3').textContent=b.title;detail.querySelector('.detail-summary').textContent=b.summary;detail.querySelector('.detail-fields').innerHTML=b.fields.map(x=>`<li><code>${x}</code></li>`).join('');detail.querySelector('.detail-invariant').textContent=b.invariant;detail.querySelector('.label').textContent=b.group==='identity'?'Envelope and scope':b.group==='graph'?'Navigation and position':b.group==='authority'?'Authority and state':'Projection and budget';}
    function draw(ctxArg,w,h){w=Number.isFinite(w)?w:bounds.width;h=Number.isFinite(h)?h:bounds.height;if(!w||!h)return;bounds={width:w,height:h};const ctx=ctxArg||canvas.getContext('2d');ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(83,211,167,.035)';for(let x=24;x<w;x+=36)for(let y=24;y<h;y+=36){ctx.beginPath();ctx.arc(x,y,1,0,Math.PI*2);ctx.fill()}const center={x:w/2,y:h/2,r:48};for(const n of nodes)arrow(ctx,center,n,'rgba(156,176,189,.24)');ctx.beginPath();ctx.arc(center.x,center.y,center.r,0,Math.PI*2);ctx.fillStyle='rgba(83,211,167,.12)';ctx.fill();ctx.strokeStyle=C.accent;ctx.lineWidth=2.5;ctx.stroke();ctx.fillStyle=C.text;ctx.textAlign='center';ctx.font='800 16px system-ui';ctx.fillText('ORBIT',center.x,center.y-4);ctx.font='11px system-ui';ctx.fillStyle=C.muted;ctx.fillText('backend node',center.x,center.y+15);
      for(const n of nodes){const col=color(n.group),active=n.id===selected;ctx.save();ctx.shadowColor=active?col:'transparent';ctx.shadowBlur=active?20:0;roundedRect(ctx,n.x-n.w/2,n.y-n.h/2,n.w,n.h,12);ctx.fillStyle=active?`${col}22`:'rgba(16,31,44,.96)';ctx.fill();ctx.strokeStyle=col;ctx.lineWidth=active?2.5:1.4;ctx.stroke();ctx.restore();ctx.fillStyle=col;ctx.font='700 10px ui-monospace,monospace';ctx.textAlign='center';ctx.fillText(n.group.toUpperCase(),n.x,n.y-15);ctx.fillStyle=C.text;ctx.font='700 13px system-ui';const lines=wrapText(ctx,n.title,n.w-20).slice(0,2);lines.forEach((line,i)=>ctx.fillText(line,n.x,n.y+5+i*15));}
    }
    const resize=hiDpi(canvas,(ctx,w,h)=>{bounds={width:w,height:h};if(!nodes.length)reset();else draw(ctx,w,h)});const hit=(x,y)=>[...nodes].reverse().find(n=>Math.abs(x-n.x)<=n.w/2&&Math.abs(y-n.y)<=n.h/2);
    canvas.addEventListener('pointerdown',e=>{const p=point(canvas,e),n=hit(p.x,p.y);if(!n)return;selected=n.id;dragging=n;offset={x:p.x-n.x,y:p.y-n.y};canvas.setPointerCapture(e.pointerId);update();draw()});canvas.addEventListener('pointermove',e=>{const p=point(canvas,e);if(dragging){dragging.x=Math.max(dragging.w/2+8,Math.min(bounds.width-dragging.w/2-8,p.x-offset.x));dragging.y=Math.max(dragging.h/2+8,Math.min(bounds.height-dragging.h/2-8,p.y-offset.y));draw()}else canvas.style.cursor=hit(p.x,p.y)?'grab':'default'});const stop=e=>{if(!dragging)return;dragging=null;try{canvas.releasePointerCapture(e.pointerId)}catch(_){}};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);document.getElementById('resetNodeLayout')?.addEventListener('click',reset);window.addEventListener('orientationchange',()=>setTimeout(()=>{resize();reset()},100));update();
  }

  function initPlanesCanvas(){
    const canvas=document.getElementById('planesCanvas'),detail=document.getElementById('planeDetail');if(!canvas||!detail)return;
    const original=[{id:'root',label:'Root index',x:.12,y:.34,r:43},{id:'repo',label:'Repository identity',x:.35,y:.18,r:46},{id:'core',label:'Core specification',x:.36,y:.53,r:48},{id:'authority',label:'Authority & safety',x:.65,y:.24,r:47},{id:'projection',label:'Projection & conformance',x:.70,y:.58,r:50},{id:'governance',label:'Governance & future tooling',x:.89,y:.38,r:47}];
    const edges={structural:[['root','repo'],['root','core'],['core','authority'],['core','projection'],['projection','governance']],routing:[['repo','core','need normative contract'],['authority','projection','need warning or gate'],['projection','core','verify source rules'],['governance','repo','re-orient']],semantic:[['repo','governance'],['authority','core'],['projection','authority'],['governance','projection']]};
    let nodes=[],active=new Set(['structural','routing','semantic']),selected='root',dragging=null,offset={x:0,y:0},bounds={width:0,height:0};
    function reset(){nodes=original.map(n=>({...n,px:n.x*bounds.width,py:n.y*bounds.height}));draw();}
    function update(){const n=nodes.find(x=>x.id===selected)||nodes[0];detail.querySelector('h3').textContent=n.label;detail.querySelector('.detail-summary').textContent=n.id==='root'?'Entry point that routes a consumer toward the smallest useful orientation surface.':'Synthetic orientation node used to demonstrate plane separation.';detail.querySelector('.node-metadata').innerHTML=`<div><dt>Structural plane</dt><dd>Containment and DAG navigation</dd></div><div><dt>Routing plane</dt><dd>Condition-gated attention hints</dd></div><div><dt>Semantic plane</dt><dd>Lateral association only</dd></div><div><dt>Selected node</dt><dd>${n.id}</dd></div>`;}
    function draw(ctxArg,w,h){w=Number.isFinite(w)?w:bounds.width;h=Number.isFinite(h)?h:bounds.height;if(!w||!h)return;bounds={width:w,height:h};const ctx=ctxArg||canvas.getContext('2d');ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(108,168,255,.08)';for(let x=0;x<w;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(active.has('structural'))for(const [a,b] of edges.structural){const n1=nodes.find(n=>n.id===a),n2=nodes.find(n=>n.id===b);arrow(ctx,{x:n1.px,y:n1.py,r:n1.r},{x:n2.px,y:n2.py,r:n2.r},'rgba(108,168,255,.62)')}if(active.has('routing'))for(const [a,b,label] of edges.routing){const n1=nodes.find(n=>n.id===a),n2=nodes.find(n=>n.id===b);arrow(ctx,{x:n1.px,y:n1.py,r:n1.r},{x:n2.px,y:n2.py,r:n2.r},'rgba(233,183,91,.60)',true,label)}if(active.has('semantic'))for(const [a,b] of edges.semantic){const n1=nodes.find(n=>n.id===a),n2=nodes.find(n=>n.id===b);ctx.save();ctx.strokeStyle='rgba(178,147,255,.42)';ctx.lineWidth=1.5;ctx.setLineDash([2,5]);ctx.beginPath();ctx.moveTo(n1.px,n1.py);ctx.lineTo(n2.px,n2.py);ctx.stroke();ctx.restore()}
      for(const n of nodes){const activeNode=n.id===selected;ctx.save();ctx.shadowColor=activeNode?C.accent:'transparent';ctx.shadowBlur=activeNode?20:0;ctx.beginPath();ctx.arc(n.px,n.py,n.r,0,Math.PI*2);ctx.fillStyle=activeNode?'rgba(83,211,167,.16)':'rgba(16,31,44,.96)';ctx.fill();ctx.strokeStyle=activeNode?C.accent:C.text;ctx.lineWidth=activeNode?2.8:1.3;ctx.stroke();ctx.restore();ctx.fillStyle=C.text;ctx.font='700 11px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';const lines=wrapText(ctx,n.label,n.r*1.45).slice(0,3);lines.forEach((line,i)=>ctx.fillText(line,n.px,n.py+(i-(lines.length-1)/2)*14));}
    }
    const resize=hiDpi(canvas,(ctx,w,h)=>{bounds={width:w,height:h};if(!nodes.length)reset();else draw(ctx,w,h)});const hit=(x,y)=>[...nodes].reverse().find(n=>Math.hypot(x-n.px,y-n.py)<=n.r);canvas.addEventListener('pointerdown',e=>{const p=point(canvas,e),n=hit(p.x,p.y);if(!n)return;selected=n.id;dragging=n;offset={x:p.x-n.px,y:p.y-n.py};canvas.setPointerCapture(e.pointerId);update();draw()});canvas.addEventListener('pointermove',e=>{const p=point(canvas,e);if(dragging){dragging.px=Math.max(dragging.r+8,Math.min(bounds.width-dragging.r-8,p.x-offset.x));dragging.py=Math.max(dragging.r+8,Math.min(bounds.height-dragging.r-8,p.y-offset.y));draw()}else canvas.style.cursor=hit(p.x,p.y)?'grab':'default'});const stop=e=>{if(!dragging)return;dragging=null;try{canvas.releasePointerCapture(e.pointerId)}catch(_){}};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);document.querySelectorAll('.layer-button').forEach(b=>b.addEventListener('click',()=>{const layer=b.dataset.layer;if(active.has(layer)){active.delete(layer);b.classList.remove('active')}else{active.add(layer);b.classList.add('active')}draw()}));document.getElementById('resetPlaneLayout')?.addEventListener('click',reset);window.addEventListener('orientationchange',()=>setTimeout(()=>{resize();reset()},100));update();
  }

  function initProjectionLab(){
    const form=document.getElementById('projectionForm'),result=document.getElementById('projectionResult');if(!form||!result)return;const target=document.getElementById('projectionTarget'),tokens=document.getElementById('observedTokens');const gates={small_llm:500,agent:700,human:1200};const defaults={small_llm:388,agent:540,human:840};target.addEventListener('change',()=>{tokens.value=defaults[target.value]});
    form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),checked=n=>data.get(n)==='on',t=target.value,observed=Math.max(0,Number(tokens.value)||0),gate=gates[t],sourceClass=document.getElementById('sourceClass').value,sync=document.getElementById('syncState').value,severity=document.getElementById('severity').value;const failures=[];if(!checked('phase1Passed'))failures.push('Backend node has not passed Phase 1.');if(sourceClass==='derived'&&!checked('derivedFrom'))failures.push('Derived node has no provenance.derived_from evidence.');if(!checked('gateExists'))failures.push(`projection_gate_tokens.${t} is missing; max_tokens is not a fallback.`);if(!checked('backendExcluded'))failures.push('Backend-only blocks remain in the client projection.');if(t==='small_llm'&&checked('anchorsRequired')&&!checked('anchorsSurvive'))failures.push('A required anchor or approved alias is missing from the emitted brief.');if(checked('gateExists')&&observed>gate)failures.push(`Observed projection ${observed} exceeds the ${gate}-token hard gate.`);const pass=failures.length===0,badge=result.querySelector('.result-badge');badge.className=`result-badge ${pass?'pass':'fail'}`;badge.textContent=pass?'Synthetic pass':'Synthetic fail';result.querySelector('h3').textContent=pass?'Projection conditions satisfied':'Projection blocked';result.querySelector('p').textContent=pass?'This bounded browser model permits emission. It is not an official compiler or validator.':`${failures.length} blocking condition${failures.length===1?'':'s'} detected.`;result.querySelector('ul').innerHTML=(pass?['No synthetic blocking findings.']:failures).map(x=>`<li>${x}</li>`).join('');const warnings=[];if(sourceClass==='derived')warnings.push('Derived, not source truth. Verify claims against source_refs_minimal.');else warnings.push('Source-truth node within its declared scope.');if(sync!=='clean')warnings.push(`Sync state is ${sync}.`);const safe=severity==='critical'?'not_safe':severity==='high'||severity==='medium'?'navigation_only':'evidence_route';warnings.push(`Invalidation severity ${severity}; safe_to_use_as ${safe}.`);const preview={target:t,source_class:sourceClass,includes:['id','title','covers','excludes','global_position','use_when','avoid_when','brief','client_warnings','source_refs_minimal'],excludes:['sync','invalidation','budget','anchors','links.semantic','consumer_briefs.human'],client_warnings:warnings,token_receipt:`${observed}/${gate}`,status:pass?'synthetic_pass':'synthetic_fail'};document.getElementById('projectionPreview').textContent=JSON.stringify(preview,null,2);document.getElementById('projectionStatus').textContent=pass?'passed':'failed';document.getElementById('projectionReceipt').textContent=`${observed} / ${gate}`;});
  }

  function initLineageCanvas(){
    const canvas=document.getElementById('lineageCanvas'),detail=document.getElementById('lineageDetail');if(!canvas||!detail)return;
    const original=[
      {id:'concept',label:'Orientation-node concept',group:'origin',x:.10,y:.28,r:45,summary:'The problem framing: consumers need bounded orientation, exclusions, authority and next routes, not always the full content.',type:'Conceptual precursor',evidence:'CONCEPT.md'},
      {id:'review',label:'Phase 3 review\n28 Jul',group:'core',x:.31,y:.16,r:46,summary:'Twelve promotion gates passed under recorded Manual Conformance, including three positive and two negative cases.',type:'Acceptance evidence',evidence:'Reviewed commit 55f1ec8…'},
      {id:'accepted',label:'ORBIT v0.1\nACCEPTED',group:'core',x:.47,y:.38,r:58,summary:'Accepted implementation-neutral specification and Manual Conformance Profile.',type:'Normative specification',evidence:'Acceptance date 28 July 2026'},
      {id:'self',label:'Self-orientation\n6 nodes',group:'experimental',x:.67,y:.18,r:47,summary:'Experimental derived navigation package that dogfoods ORBIT without becoming normative source truth.',type:'Experimental reference',evidence:'orbit/root-index.yaml'},
      {id:'adoption',label:'4 adoption\nprofiles',group:'experimental',x:.73,y:.48,r:43,summary:'Repository orientation, agent onboarding, Personal RAG and Observation Flow overlays.',type:'Experimental adoption',evidence:'examples/adoption/profiles.yaml'},
      {id:'corpus',label:'C6-C21\nextended corpus',group:'experimental',x:.56,y:.70,r:45,summary:'Sixteen focused positive and negative controls extending the accepted five-case manual corpus.',type:'Experimental evidence',evidence:'EXTENDED-CONFORMANCE-CORPUS.md'},
      {id:'library',label:'orbit-library',group:'library',x:.85,y:.70,r:48,summary:'Separate maintained library for reusable ORBIT-structured packages and reviewed managed copies.',type:'Operational package library',evidence:'orbit-library main'},
      {id:'ie',label:'IE package\n0.1.1',group:'library',x:.91,y:.36,r:43,summary:'Initial maintained package with six orientation nodes and a local-overlay seed profile.',type:'Library package',evidence:'Source-reported validation: 15 YAML, 6 nodes, 0 warnings'}
    ];
    const edges=[['concept','review','hardened into'],['review','accepted','promoted'],['accepted','self','dogfooded by'],['accepted','adoption','extended by'],['accepted','corpus','tested by'],['accepted','library','structures'],['library','ie','packages']];let nodes=[],filter='all',selected='accepted',dragging=null,offset={x:0,y:0},bounds={width:0,height:0};const visible=n=>filter==='all'||n.group===filter||n.id==='accepted';const col=g=>g==='origin'?C.blue:g==='core'?C.accent:g==='experimental'?C.amber:C.violet;
    function reset(){nodes=original.map(n=>({...n,px:n.x*bounds.width,py:n.y*bounds.height}));draw();}function update(){const n=nodes.find(x=>x.id===selected)||nodes.find(x=>x.id==='accepted');detail.querySelector('h3').textContent=n.label.replace('\n',' ');detail.querySelector('.detail-summary').textContent=n.summary;detail.querySelector('.label').textContent=n.group==='core'?'Accepted core and evidence':n.group;detail.querySelector('.node-metadata').innerHTML=`<div><dt>Artefact type</dt><dd>${n.type}</dd></div><div><dt>Evidence basis</dt><dd>${n.evidence}</dd></div><div><dt>Authority</dt><dd>${n.group==='core'?'See SPEC-STATUS for exact status':'Does not redefine ORBIT Core'}</dd></div>`;}
    function draw(ctxArg,w,h){w=Number.isFinite(w)?w:bounds.width;h=Number.isFinite(h)?h:bounds.height;if(!w||!h)return;bounds={width:w,height:h};const ctx=ctxArg||canvas.getContext('2d');ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(108,168,255,.08)';for(let x=0;x<w;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}for(const [a,b,label] of edges){const n1=nodes.find(n=>n.id===a),n2=nodes.find(n=>n.id===b);if(n1&&n2&&visible(n1)&&visible(n2))arrow(ctx,{x:n1.px,y:n1.py,r:n1.r},{x:n2.px,y:n2.py,r:n2.r},'rgba(156,176,189,.42)',false,label)}for(const n of nodes){if(!visible(n))continue;const c=col(n.group),active=n.id===selected;ctx.save();ctx.shadowColor=active?c:'transparent';ctx.shadowBlur=active?23:0;ctx.beginPath();ctx.arc(n.px,n.py,n.r,0,Math.PI*2);ctx.fillStyle=active?`${c}26`:'rgba(16,31,44,.95)';ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=active?3:1.5;ctx.stroke();ctx.restore();ctx.fillStyle=C.text;ctx.font=`700 ${n.id==='accepted'?14:11}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';const lines=n.label.split('\n').flatMap(t=>wrapText(ctx,t,n.r*1.45)).slice(0,3);lines.forEach((line,i)=>ctx.fillText(line,n.px,n.py+(i-(lines.length-1)/2)*14));}}
    const resize=hiDpi(canvas,(ctx,w,h)=>{bounds={width:w,height:h};if(!nodes.length)reset();else draw(ctx,w,h)});const hit=(x,y)=>[...nodes].reverse().find(n=>visible(n)&&Math.hypot(x-n.px,y-n.py)<=n.r);canvas.addEventListener('pointerdown',e=>{const p=point(canvas,e),n=hit(p.x,p.y);if(!n)return;selected=n.id;dragging=n;offset={x:p.x-n.px,y:p.y-n.py};canvas.setPointerCapture(e.pointerId);update();draw()});canvas.addEventListener('pointermove',e=>{const p=point(canvas,e);if(dragging){dragging.px=Math.max(dragging.r+8,Math.min(bounds.width-dragging.r-8,p.x-offset.x));dragging.py=Math.max(dragging.r+8,Math.min(bounds.height-dragging.r-8,p.y-offset.y));draw()}else canvas.style.cursor=hit(p.x,p.y)?'grab':'default'});const stop=e=>{if(!dragging)return;dragging=null;try{canvas.releasePointerCapture(e.pointerId)}catch(_){}};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);document.querySelectorAll('.graph-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.graph-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;const n=nodes.find(x=>x.id===selected);if(!n||!visible(n))selected='accepted';update();draw()}));document.getElementById('resetLineageLayout')?.addEventListener('click',reset);window.addEventListener('orientationchange',()=>setTimeout(()=>{resize();reset()},100));update();
  }

  function initCharts(){
    if(typeof Chart==='undefined')return;Chart.defaults.color=C.muted;Chart.defaults.borderColor='rgba(156,176,189,.18)';Chart.defaults.font.family='Inter,ui-sans-serif,system-ui,sans-serif';const tokenCanvas=document.getElementById('tokenChart'),maturityCanvas=document.getElementById('maturityChart');if(!tokenCanvas||!maturityCanvas)return;
    const tokenChart=new Chart(tokenCanvas,{type:'bar',data:{labels:['Formula 1','Formula 2','Formula 3'],datasets:[{label:'Observed fallback tokens',data:[950,388,158],backgroundColor:['rgba(108,168,255,.65)','rgba(83,211,167,.65)','rgba(178,147,255,.65)']},{label:'Hard gate',data:[1200,500,500],backgroundColor:'rgba(156,176,189,.20)',borderColor:'rgba(156,176,189,.55)',borderWidth:1}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,title:{display:true,text:'char/4 fallback tokens'}},x:{title:{display:true,text:'Acceptance receipt'}}},plugins:{tooltip:{callbacks:{afterLabel:c=>c.datasetIndex===0?['Backend required surface','Small-LLM projection','Small-LLM attention fields'][c.dataIndex]:'Normative ceiling'}}}}});
    const maturityChart=new Chart(maturityCanvas,{type:'radar',data:{labels:['Core specification','Manual conformance','Reference artefacts','Self-orientation','Adoption packages','Official executable tooling'],datasets:[{label:'Current source-registry maturity',data:[4,4,4,2,2,0],borderColor:C.accent,backgroundColor:'rgba(83,211,167,.15)',pointBackgroundColor:C.accent,pointBorderColor:C.bg,pointRadius:4,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,scales:{r:{beginAtZero:true,min:0,max:4,ticks:{stepSize:1,backdropColor:'transparent'},pointLabels:{color:C.text,font:{size:11,weight:'600'}},grid:{color:'rgba(156,176,189,.18)'},angleLines:{color:'rgba(156,176,189,.18)'}}},plugins:{legend:{position:'bottom',labels:{usePointStyle:true}},tooltip:{callbacks:{afterLabel:c=>c.dataIndex===5?'Validator, compiler, runtime and CI conformance remain deferred.':'Status coding from SPEC-STATUS, not measured efficacy.'}}}}});
    function exportChart(chart,name){const a=document.createElement('a');a.download=name;a.href=chart.toBase64Image('image/png',1);a.click()}document.getElementById('exportTokenChart')?.addEventListener('click',()=>exportChart(tokenChart,'orbit-token-gate-receipts.png'));document.getElementById('exportMaturityChart')?.addEventListener('click',()=>exportChart(maturityChart,'orbit-maturity-surface.png'));
  }

  setupScroll();initNodeCanvas();initPlanesCanvas();initProjectionLab();initLineageCanvas();initCharts();
})();
