(() => {
  'use strict';
  const D = window.DialecticProfile = window.DialecticProfile || {};
  D.C = { bg:'#071018', panel:'#101f2c', text:'#eaf2f7', muted:'#9cb0bd', accent:'#53d3a7', blue:'#6ca8ff', amber:'#e9b75b', violet:'#b293ff', danger:'#f27f7f', success:'#68d391' };
  const C=D.C;
  function wrapText(ctx,text,maxWidth){const words=String(text).split(/\s+/),lines=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(line&&ctx.measureText(test).width>maxWidth){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines;}
  function point(canvas,event){const rect=canvas.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top};}
  function hiDpi(canvas,draw){const resize=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);draw(ctx,rect.width,rect.height)};new ResizeObserver(resize).observe(canvas);resize();return resize;}
  function arrow(ctx,a,b,col='rgba(156,176,189,.46)',dashed=false,label=''){const angle=Math.atan2(b.y-a.y,b.x-a.x),ar=a.r||46,br=b.r||46,sx=a.x+Math.cos(angle)*ar*.82,sy=a.y+Math.sin(angle)*ar*.82,ex=b.x-Math.cos(angle)*br*.82,ey=b.y-Math.sin(angle)*br*.82;ctx.save();ctx.strokeStyle=col;ctx.lineWidth=1.8;if(dashed)ctx.setLineDash([7,6]);ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(ex,ey);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(ex,ey);ctx.lineTo(ex-Math.cos(angle-Math.PI/6)*9,ey-Math.sin(angle-Math.PI/6)*9);ctx.lineTo(ex-Math.cos(angle+Math.PI/6)*9,ey-Math.sin(angle+Math.PI/6)*9);ctx.closePath();ctx.fill();if(label){ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillStyle=C.muted;ctx.fillText(label,(sx+ex)/2,(sy+ey)/2-6)}ctx.restore();}
  D.initGraph=function({canvasId,detailId,resetId,nodes:sourceNodes,edges,filterSelector,defaultSelected='subject'}){
    const canvas=document.getElementById(canvasId),detail=document.getElementById(detailId);if(!canvas||!detail)return;
    let nodes=[],bounds={width:0,height:0},selected=defaultSelected,dragging=null,offset={x:0,y:0},filter='all';
    const visible=n=>filter==='all'||n.group===filter||n.id===defaultSelected;
    const color=g=>g==='contract'?C.accent:g==='atom'?C.blue:g==='projection'?C.violet:g==='control'?C.amber:g==='evidence'?C.success:C.muted;
    function reset(){nodes=sourceNodes.map(n=>({...n,px:n.x*bounds.width,py:n.y*bounds.height}));draw();update();}
    function update(){const n=nodes.find(x=>x.id===selected)||nodes.find(x=>x.id===defaultSelected)||nodes[0];if(!n)return;detail.querySelector('h3').textContent=n.label.replace(/\n/g,' ');detail.querySelector('.detail-summary').textContent=n.summary||'';detail.querySelector('.label').textContent=n.groupLabel||n.group;const dl=detail.querySelector('.node-metadata');if(dl)dl.innerHTML=(n.meta||[]).map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');const list=detail.querySelector('.detail-list');if(list)list.innerHTML=(n.items||[]).map(x=>`<li>${x}</li>`).join('');}
    function draw(ctxArg,w,h){bounds={width:w,height:h};const ctx=ctxArg||canvas.getContext('2d');ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(83,211,167,.032)';for(let x=24;x<w;x+=36)for(let y=24;y<h;y+=36){ctx.beginPath();ctx.arc(x,y,1,0,Math.PI*2);ctx.fill()}for(const e of edges){const a=nodes.find(n=>n.id===e[0]),b=nodes.find(n=>n.id===e[1]);if(!a||!b||!visible(a)||!visible(b))continue;arrow(ctx,{x:a.px,y:a.py,r:a.r||46},{x:b.px,y:b.py,r:b.r||46},e[3]||'rgba(156,176,189,.42)',Boolean(e[4]),e[2]||'')}for(const n of nodes){if(!visible(n))continue;const col=color(n.group),active=n.id===selected;ctx.save();ctx.shadowColor=active?col:'transparent';ctx.shadowBlur=active?22:0;ctx.beginPath();ctx.arc(n.px,n.py,n.r||46,0,Math.PI*2);ctx.fillStyle=active?`${col}26`:'rgba(16,31,44,.96)';ctx.fill();ctx.strokeStyle=col;ctx.lineWidth=active?3:1.5;ctx.stroke();ctx.restore();ctx.fillStyle=C.text;ctx.font=`700 ${n.id===defaultSelected?14:11}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';const lines=n.label.split('\n').flatMap(t=>wrapText(ctx,t,(n.r||46)*1.45)).slice(0,3);lines.forEach((line,i)=>ctx.fillText(line,n.px,n.py+(i-(lines.length-1)/2)*14));}}
    const resize=hiDpi(canvas,(ctx,w,h)=>{bounds={width:w,height:h};if(!nodes.length)reset();else draw(ctx,w,h)});const hit=(x,y)=>[...nodes].reverse().find(n=>visible(n)&&Math.hypot(x-n.px,y-n.py)<=n.r);
    canvas.addEventListener('pointerdown',e=>{const p=point(canvas,e),n=hit(p.x,p.y);if(!n)return;selected=n.id;dragging=n;offset={x:p.x-n.px,y:p.y-n.py};canvas.setPointerCapture(e.pointerId);update();draw()});canvas.addEventListener('pointermove',e=>{const p=point(canvas,e);if(dragging){dragging.px=Math.max(dragging.r+8,Math.min(bounds.width-dragging.r-8,p.x-offset.x));dragging.py=Math.max(dragging.r+8,Math.min(bounds.height-dragging.r-8,p.y-offset.y));draw()}else canvas.style.cursor=hit(p.x,p.y)?'grab':'default'});const stop=e=>{if(!dragging)return;dragging=null;try{canvas.releasePointerCapture(e.pointerId)}catch(_){}};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);document.getElementById(resetId)?.addEventListener('click',reset);if(filterSelector)document.querySelectorAll(filterSelector).forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll(filterSelector).forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;const current=nodes.find(x=>x.id===selected);if(!current||!visible(current))selected=defaultSelected;draw();update()}));window.addEventListener('orientationchange',()=>setTimeout(()=>{resize();reset()},120));update();
  };
})();
