(() => {
  'use strict';
  const D=window.DialecticProfile=window.DialecticProfile||{};
  const by=id=>document.getElementById(id);
  D.setupScroll=()=>document.querySelectorAll('[data-scroll-target]').forEach(btn=>btn.addEventListener('click',()=>by(btn.dataset.scrollTarget)?.scrollIntoView({behavior:'smooth'})));
  D.initScratchLab=()=>{const form=by('scratchForm');if(!form)return;const render=()=>{const parts=[`Subject: ${by('scratchSubject').value.trim()}`];const pairs=[['Background',by('scratchContext').value],['Prior thinking',by('scratchPrior').value],['Previous interpretation',by('scratchPrevious').value],['Accumulated findings',by('scratchFinding').value]];pairs.forEach(([k,v])=>{if(v.trim())parts.push(`${k}:\n${v.trim()}`)});parts.push('\nIteration 2/5. Deepen your understanding. What do you see now that you did not before?');by('scratchOutput').textContent=parts.join('\n\n');};form.addEventListener('submit',e=>{e.preventDefault();render();});render();};
  D.initConvergenceLab=()=>{const form=by('convergenceForm');if(!form)return;const sync=()=>{by('similarityValue').textContent=Number(by('convSimilarity').value).toFixed(2);by('thresholdValue').textContent=Number(by('convThreshold').value).toFixed(2);};['convSimilarity','convThreshold'].forEach(id=>by(id).addEventListener('input',sync));const evaluate=()=>{const iteration=Number(by('convIteration').value),max=Number(by('convMax').value),sim=Number(by('convSimilarity').value),threshold=Number(by('convThreshold').value),synth=by('convSynth').checked,done=by('convDone').checked;let reason='CONTINUE',why='No stop condition is satisfied.';if(done){reason='EXPLICIT_DONE';why='The encounter response returned is_complete=true.';}else if(iteration>1&&(synth||sim>=threshold)){reason='STABLE';why=synth?'The synthesis call returned has_converged=true.':`Similarity ${sim.toFixed(2)} meets threshold ${threshold.toFixed(2)}.`;}else if(iteration>=max){reason='MAX_ITERATIONS';why=`The iteration bound ${max} has been reached.`;}const stop=reason!=='CONTINUE';by('convHeading').textContent=reason;const badge=by('convVerdict');badge.textContent=stop?'STOP':'REPEAT';badge.className=`verdict ${reason==='CONTINUE'?'warn':reason==='MAX_ITERATIONS'?'warn':'pass'}`;by('convOutput').textContent=`iteration=${iteration}\nmax_iterations=${max}\nsimilarity=${sim.toFixed(2)}\nthreshold=${threshold.toFixed(2)}\nsynthesis_converged=${synth}\nexplicit_done=${done}\n\n${why}`;};form.addEventListener('submit',e=>{e.preventDefault();evaluate();});sync();evaluate();};
  D.initRigLab=()=>{const form=by('rigForm');if(!form)return;const populate=(id,values)=>{const el=by(id);values.forEach(v=>{const o=document.createElement('option');o.value=o.textContent=v;el.appendChild(o);});};populate('rigTemporal',D.rigEnums.temporal);populate('rigHermeneutic',D.rigEnums.hermeneutic);populate('rigDidactic',D.rigEnums.didactic);populate('rigContent',D.rigEnums.content);const render=()=>{const description=by('rigDescription').value.trim();const output=`[${by('rigTemporal').value}/${by('rigHermeneutic').value}/${by('rigDidactic').value}] ${by('rigContent').value}: ${description}`;by('rigOutput').textContent=output;const valid=/^\[[A-Z_]+\/[A-Z_]+\/[A-Z_]+\]\s+[A-Z_]+:\s+.+$/.test(output);by('rigStatus').textContent=valid?'Browser-local shape check: syntactically compatible with the source regex form.':'Browser-local shape check: incomplete.';};form.addEventListener('submit',e=>{e.preventDefault();render();});render();};
})();
