(() => {
  'use strict';
  const R=window.RigVedanProfile=window.RigVedanProfile||{};
  const by=id=>document.getElementById(id);
  const pattern=/^\[([A-Z_]+)\/([A-Z_]+)\/([A-Z_]+)\]\s*([A-Z_]+):\s*(.+)$/;
  function populate(id,values){const el=by(id);values.forEach(v=>{const o=document.createElement('option');o.value=o.textContent=v;el.appendChild(o);});}
  function parseLine(line){const m=String(line).trim().match(pattern);if(!m)return null;const [_,temporal,hermeneutic,didactic,content_type,description]=m;if(!R.enums.temporal.includes(temporal)||!R.enums.hermeneutic.includes(hermeneutic)||!R.enums.didactic.includes(didactic)||!R.enums.content.includes(content_type))return null;return{temporal,hermeneutic,didactic,content_type,description:description.trim(),metadata:{}};}
  function format(u){return`[${u.temporal}/${u.hermeneutic}/${u.didactic}] ${u.content_type}: ${u.description}`;}
  R.setupScroll=()=>document.querySelectorAll('[data-scroll-target]').forEach(btn=>btn.addEventListener('click',()=>by(btn.dataset.scrollTarget)?.scrollIntoView({behavior:'smooth'})));
  R.initBuilder=()=>{['builderTemporal','builderHermeneutic','builderDidactic','builderContent'].forEach((id,i)=>populate(id,[R.enums.temporal,R.enums.hermeneutic,R.enums.didactic,R.enums.content][i]));const form=by('builderForm');const render=()=>{const unit={temporal:by('builderTemporal').value,hermeneutic:by('builderHermeneutic').value,didactic:by('builderDidactic').value,content_type:by('builderContent').value,description:by('builderDescription').value.trim(),metadata:{source:'synthetic-browser-example'}};const text=format(unit),parsed=parseLine(text);by('builderText').textContent=text;by('builderObject').textContent=JSON.stringify(unit,null,2);const badge=by('builderVerdict');badge.textContent=parsed?'PARSED':'REJECTED';badge.className=`verdict ${parsed?'pass':'fail'}`;};form.addEventListener('submit',e=>{e.preventDefault();render();});render();};
  R.initParser=()=>{const form=by('parserForm');const run=()=>{const lines=by('parserInput').value.split(/\r?\n/),units=[],skipped=[];lines.forEach((line,index)=>{const unit=parseLine(line);if(unit)units.push(unit);else if(line.trim())skipped.push({line:index+1,text:line});});by('parserOutput').textContent=JSON.stringify({parsed_count:units.length,skipped_count:skipped.length,units,skipped},null,2);by('parserVerdict').textContent=`${units.length} PARSED / ${skipped.length} SKIPPED`;by('parserVerdict').className=`verdict ${skipped.length?'warn':'pass'}`;};form.addEventListener('submit',e=>{e.preventDefault();run();});run();};
  R.initRoundTrip=()=>{const form=by('roundTripForm');const run=()=>{const original={temporal:by('rtTemporal').value,hermeneutic:by('rtHermeneutic').value,didactic:by('rtDidactic').value,content_type:by('rtContent').value,description:by('rtDescription').value.trim(),metadata:{source:'synthetic',confidence_note:'metadata survives dictionary route'}};const dict=JSON.parse(JSON.stringify(original)),text=format(dict),parsed=parseLine(text);by('roundTripOutput').textContent=JSON.stringify({original_object:original,dictionary_round_trip:dict,formatted_text:text,parsed_from_text:parsed,metadata_preserved_in_dictionary:JSON.stringify(original.metadata)===JSON.stringify(dict.metadata),metadata_preserved_in_text:Boolean(parsed&&Object.keys(parsed.metadata).length)},null,2);const badge=by('roundTripVerdict');badge.textContent='BOUNDED ROUND TRIP';badge.className='verdict warn';};['rtTemporal','rtHermeneutic','rtDidactic','rtContent'].forEach((id,i)=>populate(id,[R.enums.temporal,R.enums.hermeneutic,R.enums.didactic,R.enums.content][i]));form.addEventListener('submit',e=>{e.preventDefault();run();});run();};
  R.initContext=()=>{const form=by('contextForm');const run=()=>{const parsed=by('contextInput').value.split(/\r?\n/).map(parseLine).filter(Boolean),header=by('contextHeader').value.trim()||'Session state (EBNF-RV annotated):';by('contextOutput').textContent=[header,...parsed.map(u=>`    ${format(u)}`)].join('\n');by('contextVerdict').textContent=`${parsed.length} UNIT${parsed.length===1?'':'S'} FORMATTED`;};form.addEventListener('submit',e=>{e.preventDefault();run();});run();};
  R.initBridge=()=>{const form=by('bridgeForm');populate('bridgeTag',R.enums.hermeneutic);const run=()=>{const tag=by('bridgeTag').value,status=tag.toLowerCase(),restored=status.toUpperCase(),valid=R.enums.hermeneutic.includes(restored);by('bridgeOutput').textContent=JSON.stringify({tag,status_value:status,restored_tag:restored,round_trip_valid:valid,axes_transformed:['hermeneutic'],axes_not_transformed:['temporal','didactic','content_type']},null,2);};form.addEventListener('submit',e=>{e.preventDefault();run();});run();};
})();
